name: brick_ganise
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  http: ^1.4.0
  http_parser: ^4.0.0
  permission_handler: ^12.0.0+1 # To handle permissions on Android/iOS  
  url_launcher: ^6.2.5  # or latest
  flutter_image_compress: ^2.1.0
  image: ^4.1.3
  path_provider: ^2.1.2
  provider: ^6.1.1  
  dropdown_search: ^5.0.6
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
