name: brick_ganise
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  http: ^0.13.3
  http_parser: ^4.0.0
  permission_handler: ^10.2.0 # To handle permissions on Android/iOS  
  url_launcher: ^6.2.5  # or latest
  flutter_image_compress: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
